{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "posthog.fullname" . }}-secrets
  labels:
    {{- include "posthog.labels" . | nindent 4 }}
type: Opaque
stringData:
  posthog-secret: {{ .Values.posthog.secret | default (randAlphaNum 56) | quote }}
  encryption-salt-keys: {{ .Values.posthog.encryptionSaltKeys | default (randAlphaNum 32) | quote }}
  database-url: {{ include "posthog.databaseUrl" . | quote }}
  redis-url: {{ include "posthog.redisUrl" . | quote }}
  clickhouse-api-password: {{ .Values.clickhouse.apiPassword | default "apipass" | quote }}
  clickhouse-app-password: {{ .Values.clickhouse.appPassword | default "apppass" | quote }}
  {{- if .Values.minio.enabled }}
  object-storage-access-key: {{ .Values.minio.accessKey | quote }}
  object-storage-secret-key: {{ .Values.minio.secretKey | quote }}
  {{- else }}
  object-storage-access-key: {{ .Values.externalObjectStorage.accessKey | quote }}
  object-storage-secret-key: {{ .Values.externalObjectStorage.secretKey | quote }}
  {{- end }}
  {{- if .Values.seaweedfs.enabled }}
  seaweedfs-access-key: {{ .Values.seaweedfs.accessKey | quote }}
  seaweedfs-secret-key: {{ .Values.seaweedfs.secretKey | quote }}
  {{- else }}
  seaweedfs-access-key: {{ .Values.externalSeaweedfs.accessKey | default "any" | quote }}
  seaweedfs-secret-key: {{ .Values.externalSeaweedfs.secretKey | default "any" | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  postgresql-password: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
{{- end }}
